<?php
return [
    ["district_id" => 1, "name_bl" => "কক্স-বাজার সদর", "name_en" => " Cox\'s Bazar Sadar"],
    ["district_id" => 1, "name_bl" => "চকরিয়া", "name_en" => " Chakaria"],
    ["district_id" => 1, "name_bl" => "কুতুবদিয়া", "name_en" => " Kutubdia"],
    ["district_id" => 1, "name_bl" => "উকহিয়া", "name_en" => " Ukhia"],
    ["district_id" => 1, "name_bl" => "মহেশখালী", "name_en" => " Moheshkhali"],
    ["district_id" => 1, "name_bl" => "পেকুয়া", "name_en" => " Pekua"],
    ["district_id" => 1, "name_bl" => "রামু", "name_en" => " Ramu"],
    ["district_id" => 1, "name_bl" => "টেকনাফ", "name_en" => " Teknaf"],
    ["district_id" => 2, "name_bl" => "কিশোরগঞ্জ সদর", "name_en" => " Kishorganj Sadar"],
    ["district_id" => 2, "name_bl" => "করিমগঞ্জ", "name_en" => " Karimganj"],
    ["district_id" => 2, "name_bl" => "তারাইল", "name_en" => " Tarail"],
    ["district_id" => 2, "name_bl" => "হোসেনপুর", "name_en" => " Hosenpur"],
    ["district_id" => 2, "name_bl" => "পাকুন্দিয়া", "name_en" => " Pakundia"],
    ["district_id" => 2, "name_bl" => "কাটিয়াদি", "name_en" => " Katiadi"],
    ["district_id" => 2, "name_bl" => "বাজিতপুর", "name_en" => " Bajitpur"],
    ["district_id" => 2, "name_bl" => "কুলিয়ারচর", "name_en" => " KuliarChar"],
    ["district_id" => 2, "name_bl" => "ভৈরব", "name_en" => " Voirab"],
    ["district_id" => 2, "name_bl" => "নিকিল", "name_en" => " Nikli"],
    ["district_id" => 2, "name_bl" => "মিঠামইন", "name_en" => " Mithamoyeen"],
    ["district_id" => 2, "name_bl" => "ইতনা", "name_en" => " Itna"],
    ["district_id" => 2, "name_bl" => "ওস্তগ্রাম", "name_en" => " Oshtogram"],
    ["district_id" => 3, "name_bl" => "কুড়িগ্রাম সদর", "name_en" => " Kurigram Sadar"],
    ["district_id" => 3, "name_bl" => "ভুরুঙ্গামারি", "name_en" => " Bhurungamari"],
    ["district_id" => 3, "name_bl" => "নাগেশ্বরী", "name_en" => " Nageshwari"],
    ["district_id" => 3, "name_bl" => "ফুলবাড়ি", "name_en" => " Fulbari"],
    ["district_id" => 3, "name_bl" => "রাজারহাট", "name_en" => " Rajarhat"],
    ["district_id" => 3, "name_bl" => "উলিপুর", "name_en" => " Ulipur"],
    ["district_id" => 3, "name_bl" => "ছিলমারি", "name_en" => " Chilmari"],
    ["district_id" => 3, "name_bl" => "রউমারি", "name_en" => " Roumari"],
    ["district_id" => 3, "name_bl" => "রাজিবপুর", "name_en" => " Rajibpur"],
    ["district_id" => 4, "name_bl" => "কুমিল্লা সদর", "name_en" => " Cumilla Sadar"],
    ["district_id" => 4, "name_bl" => "দেবীদার", "name_en" => " Debidar"],
    ["district_id" => 4, "name_bl" => "হোমনা", "name_en" => " Homna"],
    ["district_id" => 4, "name_bl" => "সদর দক্ষিন", "name_en" => " Sadar Dokkhin"],
    ["district_id" => 4, "name_bl" => "বরুরা", "name_en" => " Borura"],
    ["district_id" => 4, "name_bl" => "দাউদকান্দি", "name_en" => " Daudkani"],
    ["district_id" => 4, "name_bl" => "ব্রাহ্মণপাড়া", "name_en" => " Brahmanpara"],
    ["district_id" => 4, "name_bl" => "বুড়িচং", "name_en" => " Burichang"],
    ["district_id" => 4, "name_bl" => "চৌদ্দগ্রাম", "name_en" => " Choddogram"],
    ["district_id" => 4, "name_bl" => "মুরাদনগর", "name_en" => " Muradnagar"],
    ["district_id" => 4, "name_bl" => "মনোহরগঞ্জ", "name_en" => " Monohargonj"],
    ["district_id" => 4, "name_bl" => "লাকসাম", "name_en" => " Laksam"],
    ["district_id" => 4, "name_bl" => "নাঙ্গলকোট", "name_en" => " Nangalkot"],
    ["district_id" => 4, "name_bl" => "তিতাস", "name_en" => " Titas"],
    ["district_id" => 4, "name_bl" => "চান্দিনা", "name_en" => " Chandina"],
    ["district_id" => 4, "name_bl" => "মেঘনা", "name_en" => " Meghna"],
    ["district_id" => 5, "name_bl" => "কুষ্টিয়া সদর", "name_en" => " Kushtia Sadar"],
    ["district_id" => 5, "name_bl" => "কুমারখালী", "name_en" => " Kumarkhali"],
    ["district_id" => 5, "name_bl" => "খোকসা", "name_en" => " Khoksa"],
    ["district_id" => 5, "name_bl" => "মিরপুর", "name_en" => " Mirpur"],
    ["district_id" => 5, "name_bl" => "দৌলতপুর", "name_en" => " Doulatpur"],
    ["district_id" => 5, "name_bl" => "ভেড়ামারা", "name_en" => " Veramara"],
    ["district_id" => 6, "name_bl" => "খাগড়াছড়ি সদর", "name_en" => " Khagrachari Sadar"],
    ["district_id" => 6, "name_bl" => "দিঘিনালা", "name_en" => " Dighinala"],
    ["district_id" => 6, "name_bl" => "পানছড়ি", "name_en" => " Panchori"],
    ["district_id" => 6, "name_bl" => "লক্ষীছড়ি", "name_en" => " Lakshmichari"],
    ["district_id" => 6, "name_bl" => "মহালছড়ি", "name_en" => " Mohalchari"],
    ["district_id" => 6, "name_bl" => "মানিকছড়ি ", "name_en" => " Manikchari"],
    ["district_id" => 6, "name_bl" => "রামগড়", "name_en" => " Ramgar"],
    ["district_id" => 6, "name_bl" => "মাটিরাঙ্গা সদর", "name_en" => " Matiranga"],
    ["district_id" => 6, "name_bl" => "গুইমারা", "name_en" => " Guimara"],
    ["district_id" => 7, "name_bl" => "রুপসা", "name_en" => " Rupsha"],
    ["district_id" => 7, "name_bl" => "তেরখাদা", "name_en" => " Terokhada"],
    ["district_id" => 7, "name_bl" => "দিঘলিয়া", "name_en" => " Dighalia"],
    ["district_id" => 7, "name_bl" => "ফুলতলা", "name_en" => " Fultola"],
    ["district_id" => 7, "name_bl" => "ডুমুরিয়া", "name_en" => " Dumuria"],
    ["district_id" => 7, "name_bl" => "বটিয়াঘাটা", "name_en" => " Batiaghata"],
    ["district_id" => 7, "name_bl" => "দাকোপ", "name_en" => " Dakop"],
    ["district_id" => 7, "name_bl" => "পাইকগাছা", "name_en" => " Paikgacha"],
    ["district_id" => 7, "name_bl" => "কয়রা", "name_en" => " Koyra"],
    ["district_id" => 8, "name_bl" => "গাইবান্দা সদর", "name_en" => " Gaibandha Sadar"],
    ["district_id" => 8, "name_bl" => "ফুলকচি", "name_en" => " Fulkuchi"],
    ["district_id" => 8, "name_bl" => "সাঘাটা ", "name_en" => " Shaghata"],
    ["district_id" => 8, "name_bl" => "গোবিন্দগঞ্জ", "name_en" => " Gobindaganj"],
    ["district_id" => 8, "name_bl" => "পলাশবাড়ী ", "name_en" => " Palashbari"],
    ["district_id" => 8, "name_bl" => "সাদুল্লাপুর", "name_en" => " Shadullapur"],
    ["district_id" => 8, "name_bl" => "সুন্দরগঞ্জ", "name_en" => " Shundarganj"],
    ["district_id" => 9, "name_bl" => "গাজীপুুর সদর", "name_en" => " Gazipur Sadar"],
    ["district_id" => 9, "name_bl" => "কালিয়াকৈর", "name_en" => " Kaliakair"],
    ["district_id" => 9, "name_bl" => "শ্রিপুর", "name_en" => " Sreepur"],
    ["district_id" => 9, "name_bl" => "কাপাসিয়া", "name_en" => " Kapasia"],
    ["district_id" => 9, "name_bl" => "কালিগঞ্জ", "name_en" => " Kaliganj"],
    ["district_id" => 10, "name_bl" => "গোপালঞ্জ সদর", "name_en" => " Gopalganj Sadar"],
    ["district_id" => 10, "name_bl" => "কাশিয়ানি", "name_en" => " Kashiani"],
    ["district_id" => 10, "name_bl" => "টুঙ্গীপাড়া", "name_en" => " Tungipara"],
    ["district_id" => 10, "name_bl" => "কোটালিপাড়া", "name_en" => " Kotalipara"],
    ["district_id" => 10, "name_bl" => "মুকসুদপুড়", "name_en" => " Muksudpur"],
    ["district_id" => 11, "name_bl" => "রাঙ্গুনিয়া", "name_en" => " Rangunia"],
    ["district_id" => 11, "name_bl" => "সিতাকুন্ড", "name_en" => " Sitakunda"],
    ["district_id" => 11, "name_bl" => "মিরসরাই", "name_en" => " Mirsharai"],
    ["district_id" => 11, "name_bl" => "পটিয়া", "name_en" => " Patiya"],
    ["district_id" => 11, "name_bl" => "সন্দিপ", "name_en" => " Shandip"],
    ["district_id" => 11, "name_bl" => "বাশখালী", "name_en" => " Bashkhali"],
    ["district_id" => 11, "name_bl" => "বোয়ালখালী ", "name_en" => " Boalkhali"],
    ["district_id" => 11, "name_bl" => "আনোয়ারা", "name_en" => " Anwara"],
    ["district_id" => 11, "name_bl" => "সাতকানিয়া", "name_en" => " Satkania"],
    ["district_id" => 11, "name_bl" => "লোহাগড়া", "name_en" => " Lohagara"],
    ["district_id" => 11, "name_bl" => "হাটহাজারী", "name_en" => " Hathazari"],
    ["district_id" => 11, "name_bl" => "ফটিকছড়ি", "name_en" => " Fatikchhari"],
    ["district_id" => 11, "name_bl" => "রাউজান", "name_en" => " Raujan"],
    ["district_id" => 11, "name_bl" => "চন্দনাইস", "name_en" => " Chandanaish"],
    ["district_id" => 11, "name_bl" => "কর্নফুলী", "name_en" => " Karnaphuli"],
    ["district_id" => 12, "name_bl" => "চাঁদপুর সদর", "name_en" => " Chandpur Sadar"],
    ["district_id" => 12, "name_bl" => "ফরিদগঞ্জ", "name_en" => " Faridganj"],
    ["district_id" => 12, "name_bl" => "হাইমচর", "name_en" => " Haimchar"],
    ["district_id" => 12, "name_bl" => "হাজিগঞ্জ", "name_en" => " Haziganj"],
    ["district_id" => 12, "name_bl" => "কচুয়া", "name_en" => " Kochua"],
    ["district_id" => 12, "name_bl" => "মতলব দক্ষিন", "name_en" => " Motlob Dokkhin"],
    ["district_id" => 12, "name_bl" => "মতলব উত্তর", "name_en" => " Motlob Uttar"],
    ["district_id" => 12, "name_bl" => "শাহরাস্তি", "name_en" => " Shahrasti"],
    ["district_id" => 13, "name_bl" => "চাপাইনবাবগঞ্জ", "name_en" => " Chapainababganj Sadar"],
    ["district_id" => 13, "name_bl" => "শিবগঞ্জ", "name_en" => " Shibganj"],
    ["district_id" => 13, "name_bl" => "গোমসতাপুর", "name_en" => " Gomastapur"],
    ["district_id" => 13, "name_bl" => "নাচোল", "name_en" => " Nachol"],
    ["district_id" => 13, "name_bl" => "ভোলাহাট", "name_en" => " Volahat"],
    ["district_id" => 14, "name_bl" => "চুয়াডাঙ্গা সদর", "name_en" => " Chuadanga Sadar"],
    ["district_id" => 14, "name_bl" => "আমডাঙ্গা", "name_en" => " Alamdanga"],
    ["district_id" => 14, "name_bl" => "ডামুরহুদা", "name_en" => " Damurhuda"],
    ["district_id" => 14, "name_bl" => "জীবননগর", "name_en" => " Jibannagar"],
    ["district_id" => 15, "name_bl" => "জয়পুরহাট সদর", "name_en" => " Joypurhat Sadar"],
    ["district_id" => 15, "name_bl" => "পাচবিবি", "name_en" => " Pachbibi"],
    ["district_id" => 15, "name_bl" => "আক্কেলপুর", "name_en" => " Akkelpur"],
    ["district_id" => 15, "name_bl" => "কালাই", "name_en" => " Kalai"],
    ["district_id" => 15, "name_bl" => "ক্ষেতলাল", "name_en" => " Khetlal"],
    ["district_id" => 16, "name_bl" => "জামালপুর সদর", "name_en" => " Jamalpur Sadar"],
    ["district_id" => 16, "name_bl" => "মেলান্দহ", "name_en" => " Melandaha"],
    ["district_id" => 16, "name_bl" => "ইসলামপুর", "name_en" => " Islampur"],
    ["district_id" => 16, "name_bl" => "দেওয়ানগঞ্জ", "name_en" => " Dewanganj"],
    ["district_id" => 16, "name_bl" => "সরিষাবাড়ি", "name_en" => " Sharishabari"],
    ["district_id" => 16, "name_bl" => "মাদারগঞ্জ", "name_en" => " Motherganj"],
    ["district_id" => 16, "name_bl" => "বকশীগঞ্জ", "name_en" => " Baksiganj"],
    ["district_id" => 17, "name_bl" => "ঝালকাঠি সদর", "name_en" => " Jhalokati Sadar"],
    ["district_id" => 17, "name_bl" => "কাঠালিয়া", "name_en" => " Kathalia"],
    ["district_id" => 17, "name_bl" => "নলছিটি", "name_en" => " Nalchity"],
    ["district_id" => 17, "name_bl" => "রাজাপুর", "name_en" => " Rajapur"],
    ["district_id" => 18, "name_bl" => "ঝিনাইদহ সদর", "name_en" => " Jhenaidah Sadar"],
    ["district_id" => 18, "name_bl" => "কোটচাঁদপুর", "name_en" => " Kotchandpur"],
    ["district_id" => 18, "name_bl" => "মহেশপুর", "name_en" => " Moheshpur"],
    ["district_id" => 18, "name_bl" => "শৈলকুপা", "name_en" => " Soilkupa"],
    ["district_id" => 18, "name_bl" => "হরিনাকুন্ডু", "name_en" => " Horinakundu"],
    ["district_id" => 19, "name_bl" => "মধুপুর", "name_en" => " Modhupur"],
    ["district_id" => 19, "name_bl" => "ধনবাড়ি", "name_en" => " Dhanbari"],
    ["district_id" => 19, "name_bl" => "গোপালপুুর", "name_en" => " Gopalpur"],
    ["district_id" => 19, "name_bl" => "ভাপুর", "name_en" => " Vuapur"],
    ["district_id" => 19, "name_bl" => "ঘাটাইল", "name_en" => " Ghatail"],
    ["district_id" => 19, "name_bl" => "কালিহাতি", "name_en" => " Kalihati"],
    ["district_id" => 19, "name_bl" => "টাংগাইল সদর", "name_en" => " Tangail Sadar"],
    ["district_id" => 19, "name_bl" => "নাগরপুর", "name_en" => " Nagarpur"],
    ["district_id" => 19, "name_bl" => "দেলদুয়ার", "name_en" => " Delduar"],
    ["district_id" => 19, "name_bl" => "মির্জাপুর", "name_en" => " Mirzapur"],
    ["district_id" => 19, "name_bl" => "বাসাইল", "name_en" => " Basail"],
    ["district_id" => 19, "name_bl" => "শখিপুর ", "name_en" => " Shakhipur"],
    ["district_id" => 20, "name_bl" => "ঠাকুরগাঁও সদর", "name_en" => " Thakurgaon Sadar"],
    ["district_id" => 20, "name_bl" => "পীরগঞ্জ", "name_en" => " Pirganj"],
    ["district_id" => 20, "name_bl" => "রানীসংকাইল", "name_en" => " Ranisankail"],
    ["district_id" => 20, "name_bl" => "হরিপুর", "name_en" => " Horipur"],
    ["district_id" => 20, "name_bl" => "বালিয়াডাঙ্গী", "name_en" => " Baliadangi"],
    ["district_id" => 21, "name_bl" => "সাভার", "name_en" => " Savar"],
    ["district_id" => 21, "name_bl" => "নবাবগঞ্জ", "name_en" => " Nobabgonj"],
    ["district_id" => 21, "name_bl" => "দোহার", "name_en" => " Dohar"],
    ["district_id" => 21, "name_bl" => "কেরানিগঞ্জ", "name_en" => " Keraniganj"],
    ["district_id" => 21, "name_bl" => "তেজগাঁও সার্কেল", "name_en" => " Tejgaon Circle"],
    ["district_id" => 21, "name_bl" => "ধামরাই", "name_en" => " Dhamrai"],
    ["district_id" => 22, "name_bl" => "দিনাজপুর সদর", "name_en" => " Dinajpur Sadar"],
    ["district_id" => 22, "name_bl" => "বিরল", "name_en" => " Biral"],
    ["district_id" => 22, "name_bl" => "বোছাগঞ্জ", "name_en" => " Bochaganj"],
    ["district_id" => 22, "name_bl" => "কাহারোল", "name_en" => " Kaharole"],
    ["district_id" => 22, "name_bl" => "বিরগঞ্জ", "name_en" => " Birganj"],
    ["district_id" => 22, "name_bl" => "ঘোড়াঘাট", "name_en" => " Ghoraghat"],
    ["district_id" => 22, "name_bl" => "হাকিমপুর", "name_en" => " Hakimpur"],
    ["district_id" => 22, "name_bl" => "পারবতিপুর", "name_en" => " Parbatipur"],
    ["district_id" => 22, "name_bl" => "বিক্রমপুর", "name_en" => " Birampur"],
    ["district_id" => 22, "name_bl" => "খানসামা", "name_en" => " Khansama"],
    ["district_id" => 22, "name_bl" => "শ্রীবন্দর", "name_en" => " Chirirbandar"],
    ["district_id" => 3, "name_bl" => "ফুলবাড়ি", "name_en" => " Fullbari"],
    ["district_id" => 21, "name_bl" => "নবাবগঞ্জ", "name_en" => " Nobabganj"],
    ["district_id" => 23, "name_bl" => "নওগা সদর", "name_en" => " Naogaon Sadar"],
    ["district_id" => 23, "name_bl" => "বদলগাছী", "name_en" => " Badolgachi"],
    ["district_id" => 23, "name_bl" => "মহাদেবপুর", "name_en" => " Mohadevpur"],
    ["district_id" => 23, "name_bl" => "পত্নীতলা", "name_en" => " Patnitala"],
    ["district_id" => 23, "name_bl" => "ধামইরহাট", "name_en" => " Dhamoirhat"],
    ["district_id" => 23, "name_bl" => "সাপাহার", "name_en" => " Shapahar"],
    ["district_id" => 23, "name_bl" => "পরশা", "name_en" => " Porsha"],
    ["district_id" => 23, "name_bl" => " মান্দা", "name_en" => " Manda"],
    ["district_id" => 23, "name_bl" => "রানীনগর", "name_en" => " Raninagar"],
    ["district_id" => 23, "name_bl" => "আত্রাই", "name_en" => " Atrai"],
    ["district_id" => 24, "name_bl" => "নড়াইল সদর", "name_en" => " Narail Sadar"],
    ["district_id" => 15, "name_bl" => "কালাই", "name_en" => " Kalia"],
    ["district_id" => 25, "name_bl" => "নরসিংদী সদর", "name_en" => " Norshingdi Sadar"],
    ["district_id" => 25, "name_bl" => "পলাশ", "name_en" => " Polash"],
    ["district_id" => 25, "name_bl" => "শিবপুর", "name_en" => " Shibpur"],
    ["district_id" => 25, "name_bl" => "বেলাব", "name_en" => " Belabo"],
    ["district_id" => 25, "name_bl" => "মনোহরদী", "name_en" => " Monohardi"],
    ["district_id" => 25, "name_bl" => "রায়পুরা", "name_en" => " Raipura"],
    ["district_id" => 26, "name_bl" => "নাটোর সদর", "name_en" => " Natore Sadar"],
    ["district_id" => 26, "name_bl" => "সিংরা", "name_en" => " Singra"],
    ["district_id" => 26, "name_bl" => "গুরুদাসপুর", "name_en" => " Gurudaspur"],
    ["district_id" => 26, "name_bl" => "বড়াইগ্রাম", "name_en" => " Boraigram"],
    ["district_id" => 26, "name_bl" => "লালপুর", "name_en" => " Lalpur"],
    ["district_id" => 26, "name_bl" => "বাগাতিপাড়া", "name_en" => " Bagatipara"],
    ["district_id" => 26, "name_bl" => "নলডাঙ্গ", "name_en" => " Naldanga"],
    ["district_id" => 27, "name_bl" => "আড়াইহাজার", "name_en" => " Araihazar"],
    ["district_id" => 27, "name_bl" => "বান্দর", "name_en" => " Bandar"],
    ["district_id" => 27, "name_bl" => "নারায়নগঞ্জ সদর", "name_en" => " Narayanganj Sadar"],
    ["district_id" => 27, "name_bl" => "রূপগঞ্জ", "name_en" => " Rupganj"],
    ["district_id" => 27, "name_bl" => "সোনারগাঁ", "name_en" => " Sonarga"],
    ["district_id" => 28, "name_bl" => "নীলফামারি সদর", "name_en" => " Nilphamari Sadar"],
    ["district_id" => 28, "name_bl" => " সৈয়দপুর", "name_en" => " Soiyodpur"],
    ["district_id" => 28, "name_bl" => "ডিমলা ", "name_en" => " Dimla"],
    ["district_id" => 28, "name_bl" => "ডোমার", "name_en" => " Domar"],
    ["district_id" => 28, "name_bl" => "ঢালঢাকা", "name_en" => " Jaldhaka"],
    ["district_id" => 28, "name_bl" => "কিশোরগঞ্জ", "name_en" => " Kishorganj"],
    ["district_id" => 29, "name_bl" => "নেত্রকোনা", "name_en" => " Netrokona Sadar"],
    ["district_id" => 29, "name_bl" => "বারহাট্টা ", "name_en" => " Barhatta"],
    ["district_id" => 29, "name_bl" => "দুর্গাপুর ", "name_en" => " Durgapur"],
    ["district_id" => 29, "name_bl" => "কেন্দুয়া", "name_en" => " Kendua"],
    ["district_id" => 29, "name_bl" => "আটপাড়া", "name_en" => " Atpara"],
    ["district_id" => 29, "name_bl" => "মদন", "name_en" => " Madon"],
    ["district_id" => 29, "name_bl" => "খালিয়াজুরী", "name_en" => " Khaliajuri"],
    ["district_id" => 29, "name_bl" => "কলমাকান্দা", "name_en" => " Kalmakanda"],
    ["district_id" => 29, "name_bl" => "মোহনগঞ্জ", "name_en" => " Mohonganj"],
    ["district_id" => 29, "name_bl" => "পূর্বধলা", "name_en" => " Purbadhala"],
    ["district_id" => 30, "name_bl" => "নোয়াখালী সদর", "name_en" => " Noakhali Sadar"],
    ["district_id" => 30, "name_bl" => "কবিরহাট", "name_en" => " Kobirhat"],
    ["district_id" => 30, "name_bl" => "সুবর্নচর", "name_en" => " SubornoChar"],
    ["district_id" => 30, "name_bl" => "বেগমগঞ্জ", "name_en" => " Begumgonj"],
    ["district_id" => 30, "name_bl" => "সোনাইমুড়ি", "name_en" => " Sonaimuri"],
    ["district_id" => 30, "name_bl" => "চাটখিল", "name_en" => " Chatkhil"],
    ["district_id" => 30, "name_bl" => "সেনবাগ", "name_en" => " Senbag"],
    ["district_id" => 30, "name_bl" => "কোম্পানিগঞ্জ", "name_en" => " CompanyGonj"],
    ["district_id" => 30, "name_bl" => "হাতিয়া", "name_en" => " Hatia"],
    ["district_id" => 31, "name_bl" => "পঞ্চগড় সদর", "name_en" => " Panchagar Sadar"],
    ["district_id" => 31, "name_bl" => "বোদা", "name_en" => " Boda"],
    ["district_id" => 31, "name_bl" => "দেবীগঞ্জ", "name_en" => " Debiganj"],
    ["district_id" => 31, "name_bl" => "আটোরিয়া", "name_en" => " Atoria"],
    ["district_id" => 31, "name_bl" => "তেঁতুলিয়া", "name_en" => " Tetulia"],
    ["district_id" => 32, "name_bl" => "পটুয়াখালী সদর", "name_en" => " Patuakhali Sadar"],
    ["district_id" => 32, "name_bl" => "মির্জাগঞ্জ", "name_en" => " Mirzaganj"],
    ["district_id" => 32, "name_bl" => "কালাপাড়া", "name_en" => " Kalapara"],
    ["district_id" => 32, "name_bl" => "দশমিনা", "name_en" => " Doshmina"],
    ["district_id" => 32, "name_bl" => "বাউফল", "name_en" => " Bauphal"],
    ["district_id" => 32, "name_bl" => "গলাচিপা", "name_en" => " Golacipa"],
    ["district_id" => 32, "name_bl" => "রাঙ্গাবালী", "name_en" => " Rangabali"],
    ["district_id" => 32, "name_bl" => "দুমকি", "name_en" => " Dumki"],
    ["district_id" => 33, "name_bl" => "পাবনা সদর", "name_en" => " Pabna Sadar"],
    ["district_id" => 33, "name_bl" => "সুজানগর", "name_en" => " Sujanagar"],
    ["district_id" => 33, "name_bl" => "ঈশ্বরদী", "name_en" => " Ishwardi"],
    ["district_id" => 33, "name_bl" => "ভাঙ্গুরা", "name_en" => " Vangura"],
    ["district_id" => 33, "name_bl" => "বেড়া", "name_en" => " Bera"],
    ["district_id" => 33, "name_bl" => "আটঘরিয়া", "name_en" => " Atgharia"],
    ["district_id" => 33, "name_bl" => "চাটমোহর", "name_en" => " Chatmohor"],
    ["district_id" => 33, "name_bl" => "সাথিয়া", "name_en" => " Sathia"],
    ["district_id" => 33, "name_bl" => "ফরিদপুর", "name_en" => " Faridpur"],
    ["district_id" => 34, "name_bl" => "পিরোজপুর সদর", "name_en" => " Pirojpur Sadar"],
    ["district_id" => 34, "name_bl" => "নজিরপুর", "name_en" => " Najirpur"],
    ["district_id" => 34, "name_bl" => "কাউখালী", "name_en" => " Kawkhali"],
    ["district_id" => 34, "name_bl" => "ইন্দুরকানী", "name_en" => " Indurkani"],
    ["district_id" => 34, "name_bl" => "ভান্ডারিয়া", "name_en" => " Vandaria"],
    ["district_id" => 34, "name_bl" => "মাঠবাড়িয়া", "name_en" => " Mathbaria"],
    ["district_id" => 34, "name_bl" => "নেসারাবাদ", "name_en" => " Nesarabad"],
    ["district_id" => 35, "name_bl" => "ফরিদপুর সদর", "name_en" => " Faridpur Sadar"],
    ["district_id" => 35, "name_bl" => "আলফাডাঙ্গা", "name_en" => " Alfadanga"],
    ["district_id" => 35, "name_bl" => "বোয়ালমারি", "name_en" => " Boalmari"],
    ["district_id" => 35, "name_bl" => "সদরপুর", "name_en" => " Sadarpur"],
    ["district_id" => 35, "name_bl" => "নগরকান্দা", "name_en" => " Nagarkanda"],
    ["district_id" => 35, "name_bl" => "ভাংগা", "name_en" => " Vanga"],
    ["district_id" => 35, "name_bl" => "চরভদ্রাসন", "name_en" => " Charbhadrasan"],
    ["district_id" => 35, "name_bl" => "মধুুখালি", "name_en" => " Modhukhali"],
    ["district_id" => 35, "name_bl" => "শালথা", "name_en" => " Saltha"],
    ["district_id" => 36, "name_bl" => "ফেনি সদর", "name_en" => " Feni Sadar"],
    ["district_id" => 36, "name_bl" => "সোনা গাজি", "name_en" => " Sonagazi"],
    ["district_id" => 36, "name_bl" => "দাগনভূইয়া", "name_en" => " Daganbhuiyan"],
    ["district_id" => 36, "name_bl" => "ছাগলনাইয়া", "name_en" => " Chagolnaiya"],
    ["district_id" => 36, "name_bl" => "পর্শুরাম", "name_en" => " Porshuram"],
    ["district_id" => 36, "name_bl" => "ফুলগাজী", "name_en" => " Fulgazi"],
    ["district_id" => 37, "name_bl" => "বগুড়া সদর", "name_en" => " Bogra sadar"],
    ["district_id" => 37, "name_bl" => "গাবতলী", "name_en" => " Gabtali"],
    ["district_id" => 37, "name_bl" => "শেরপুর", "name_en" => " Sherpur"],
    ["district_id" => 37, "name_bl" => "কাহালু", "name_en" => " Kahaloo"],
    ["district_id" => 37, "name_bl" => "ধুনাত", "name_en" => " Dhunat"],
    ["district_id" => 37, "name_bl" => "নন্দীগ্রাম", "name_en" => " Nandigram"],
    ["district_id" => 37, "name_bl" => "সোনাতলা", "name_en" => " Sonatola"],
    ["district_id" => 37, "name_bl" => "আদমদিঘী", "name_en" => " Adamdighi"],
    ["district_id" => 37, "name_bl" => "দুপচাচিয়া", "name_en" => " Dupchachia"],
    ["district_id" => 37, "name_bl" => "সারিয়া কান্দি", "name_en" => " Sariakandi"],
    ["district_id" => 38, "name_bl" => "বরগুনা সদর", "name_en" => " Barguna Sadar"],
    ["district_id" => 38, "name_bl" => "আমতলি", "name_en" => " Amtoli"],
    ["district_id" => 38, "name_bl" => "বেতাগী", "name_en" => " Betagi"],
    ["district_id" => 38, "name_bl" => "বামনা", "name_en" => " Bamna"],
    ["district_id" => 38, "name_bl" => "পাথরঘাটা", "name_en" => " Patharghata"],
    ["district_id" => 38, "name_bl" => "তালতলী", "name_en" => " Taltoli"],
    ["district_id" => 39, "name_bl" => "বরিশাল সদর", "name_en" => " Borishal Sadar"],
    ["district_id" => 39, "name_bl" => "বাকেরগঞ্জ", "name_en" => " Bakerganj"],
    ["district_id" => 39, "name_bl" => "বাবুগঞ্জ", "name_en" => " Babuganj"],
    ["district_id" => 39, "name_bl" => "উজিরপুর", "name_en" => " Ujirpur"],
    ["district_id" => 39, "name_bl" => "বানারীপাড়া", "name_en" => " Banaripara"],
    ["district_id" => 39, "name_bl" => "গৌরনদী", "name_en" => " Gouronodi"],
    ["district_id" => 39, "name_bl" => "অঘৌইলঝাড়া", "name_en" => " Oghoiljhara"],
    ["district_id" => 39, "name_bl" => "মেহেন্দীগঞ্জ", "name_en" => " Mehendiganj"],
    ["district_id" => 39, "name_bl" => "মুলাদী", "name_en" => " Muladi"],
    ["district_id" => 39, "name_bl" => "হিজলা", "name_en" => " Hizla"],
    ["district_id" => 40, "name_bl" => "বাগেরহাট সদর", "name_en" => " Bagerhat Sadar"],
    ["district_id" => 40, "name_bl" => "ফকিরহাট", "name_en" => " Fokirhat"],
    ["district_id" => 40, "name_bl" => "মোল্লাহাট", "name_en" => " Mollahat"],
    ["district_id" => 40, "name_bl" => "চিতলমারী", "name_en" => " Chitalmari"],
    ["district_id" => 41, "name_bl" => "বান্দরবন সদর", "name_en" => " Bandarban Sadar"],
    ["district_id" => 41, "name_bl" => "আলীকদম", "name_en" => " Alikadam"],
    ["district_id" => 41, "name_bl" => "নাইক্ষ্যংছড়ি", "name_en" => " Naikkongchori"],
    ["district_id" => 41, "name_bl" => "লামা", "name_en" => " Lama"],
    ["district_id" => 41, "name_bl" => "রুমা", "name_en" => " Ruma"],
    ["district_id" => 41, "name_bl" => "থানচি", "name_en" => " Thanchi"],
    ["district_id" => 42, "name_bl" => "আখাউড়া(দঃ)", "name_en" => " Akhaura"],
    ["district_id" => 42, "name_bl" => "বাঞ্ছারামপুর", "name_en" => " Bancharampur"],
    ["district_id" => 42, "name_bl" => "ব্রাহ্মনবাড়িয়া সদর", "name_en" => " Brahmanbaria Sadar"],
    ["district_id" => 42, "name_bl" => "বিজয়নগর", "name_en" => " Bijoynagar"],
    ["district_id" => 42, "name_bl" => "আশুগঞ্জ", "name_en" => " Ashuganj"],
    ["district_id" => 42, "name_bl" => "কশবা", "name_en" => " Koshba"],
    ["district_id" => 42, "name_bl" => "নবীনগর", "name_en" => " Nobinagar"],
    ["district_id" => 42, "name_bl" => "নাসিরনগর", "name_en" => " Nasirnagar"],
    ["district_id" => 42, "name_bl" => "সরাইল", "name_en" => " Sorail"],
    ["district_id" => 43, "name_bl" => "ভোলা সদর", "name_en" => " Bhola Sadar"],
    ["district_id" => 43, "name_bl" => "বোরহানুদ্দীন", "name_en" => " Borhanuddin"],
    ["district_id" => 43, "name_bl" => "চরফ্যাশন", "name_en" => " Charfashion"],
    ["district_id" => 43, "name_bl" => "দৌলতখান", "name_en" => " Doulatkhan"],
    ["district_id" => 43, "name_bl" => "মনপুরা", "name_en" => " Monpura"],
    ["district_id" => 43, "name_bl" => "তজুমদ্দিন", "name_en" => " Tojumuddin"],
    ["district_id" => 43, "name_bl" => "লালমোহন", "name_en" => " Lalmohon"],
    ["district_id" => 44, "name_bl" => "মাগুরা সদর", "name_en" => " Magura Sadar"],
    ["district_id" => 44, "name_bl" => "সালিখা", "name_en" => " Shalikha"],
    ["district_id" => 44, "name_bl" => "মহম্মদপুর", "name_en" => " Muhammodpur"],
    ["district_id" => 45, "name_bl" => "মাদারিপুর সদর", "name_en" => " Madaripur Sadar"],
    ["district_id" => 45, "name_bl" => "রাজইর", "name_en" => " Rajoir"],
    ["district_id" => 45, "name_bl" => "শিবচর", "name_en" => " Shibchar"],
    ["district_id" => 45, "name_bl" => "কালকিনি", "name_en" => " Kalkini"],
    ["district_id" => 46, "name_bl" => "মানিকগঞ্জ সদর", "name_en" => " Manikgonj Sadar"],
    ["district_id" => 46, "name_bl" => "শিবালয়", "name_en" => " Shibaloy"],
    ["district_id" => 46, "name_bl" => "ঘিওর", "name_en" => " Ghior"],
    ["district_id" => 46, "name_bl" => "শাতুরিয়া", "name_en" => " Shaturia"],
    ["district_id" => 46, "name_bl" => "সিংগাইর", "name_en" => " Shingair"],
    ["district_id" => 46, "name_bl" => "হরিরামপুর", "name_en" => " Horirampur"],
    ["district_id" => 47, "name_bl" => "মায়মনসিংহ সদর", "name_en" => " Mymensingh Sadar"],
    ["district_id" => 47, "name_bl" => "ফুলবাড়ীয়া ", "name_en" => " Fulbaria"],
    ["district_id" => 47, "name_bl" => "ত্রিশাল", "name_en" => " Trishal"],
    ["district_id" => 47, "name_bl" => "ভালুকা", "name_en" => " Valuka"],
    ["district_id" => 47, "name_bl" => "মুকতাগাছা", "name_en" => " Muktagacha"],
    ["district_id" => 47, "name_bl" => "ধোবাউড়া", "name_en" => " Dhobaura"],
    ["district_id" => 47, "name_bl" => "ফুলপুর", "name_en" => " Fulpur"],
    ["district_id" => 47, "name_bl" => "হালুয়াঘাট", "name_en" => " Haluaghat"],
    ["district_id" => 47, "name_bl" => "গৌরীপুর", "name_en" => " Gouripur"],
    ["district_id" => 47, "name_bl" => "রসুলপুর", "name_en" => " Gafargao"],
    ["district_id" => 47, "name_bl" => "ঈশ্বরগঞ্জ", "name_en" => " Isshorganj"],
    ["district_id" => 47, "name_bl" => "নান্দাইল", "name_en" => " Nandail"],
    ["district_id" => 47, "name_bl" => "তারাকান্দা", "name_en" => " Tarakanda"],
    ["district_id" => 48, "name_bl" => "মুন্সিগঞ্জ", "name_en" => " Munshiganj Sadar"],
    ["district_id" => 48, "name_bl" => "শ্রীনগর", "name_en" => " Sreenagar"],
    ["district_id" => 48, "name_bl" => "সিরাজদিখান", "name_en" => " Sirajdikhan"],
    ["district_id" => 48, "name_bl" => "লৌহজং", "name_en" => " Lohajang"],
    ["district_id" => 48, "name_bl" => "গজারিয়া", "name_en" => " Gozaria"],
    ["district_id" => 48, "name_bl" => "টঙ্গীবাড়ি", "name_en" => " Tongibari"],
    ["district_id" => 49, "name_bl" => "মেহেরপুর সদর", "name_en" => " Meherpur Sadar"],
    ["district_id" => 49, "name_bl" => "মুজিবনগর", "name_en" => " Mujibnagar"],
    ["district_id" => 49, "name_bl" => "গাংনী", "name_en" => " Gangni"],
    ["district_id" => 50, "name_bl" => "মৌলভীবাজার", "name_en" => " Moulovibazar Sadar"],
    ["district_id" => 50, "name_bl" => "বড়লেখা", "name_en" => " Borolekha"],
    ["district_id" => 50, "name_bl" => "কমলগঞ্জ", "name_en" => " Kamolganj"],
    ["district_id" => 50, "name_bl" => "কুলাউড়া", "name_en" => " Kulaura"],
    ["district_id" => 50, "name_bl" => "রাজনগর", "name_en" => " Rajnagar"],
    ["district_id" => 50, "name_bl" => "শ্রীমঙ্গল", "name_en" => " Seemangal"],
    ["district_id" => 50, "name_bl" => "জুরি", "name_en" => " Juri"],
    ["district_id" => 51, "name_bl" => "যশোর সদর", "name_en" => " Jessor Sadar"],
    ["district_id" => 51, "name_bl" => "অভয়নগর", "name_en" => " Avoynagar"],
    ["district_id" => 51, "name_bl" => "বাঘেরপাড়া", "name_en" => " Bagherpara"],
    ["district_id" => 51, "name_bl" => "চৌগাছা", "name_en" => " Chowgacha"],
    ["district_id" => 51, "name_bl" => "ঝিকারগাছা", "name_en" => " Jhikargacha"],
    ["district_id" => 51, "name_bl" => "কেশবপুর", "name_en" => " Keshobpur"],
    ["district_id" => 51, "name_bl" => "মনিরামপুর", "name_en" => " Monirampur"],
    ["district_id" => 51, "name_bl" => "সরিষা", "name_en" => " Sharsha"],
    ["district_id" => 52, "name_bl" => "রংপুর সদর", "name_en" => " Rangpur Sadar"],
    ["district_id" => 52, "name_bl" => "গংগাচড়া", "name_en" => " Gang-gachra"],
    ["district_id" => 52, "name_bl" => "পীরগাছা", "name_en" => " Pirgacha"],
    ["district_id" => 52, "name_bl" => "কুনিয়া", "name_en" => " kaunia"],
    ["district_id" => 52, "name_bl" => "তারাগঞ্জ", "name_en" => " Taraganj"],
    ["district_id" => 52, "name_bl" => "বদরগঞ্জ", "name_en" => " Badorganj"],
    ["district_id" => 52, "name_bl" => "মিঠাপুকুর", "name_en" => " Mithapukur"],
    ["district_id" => 53, "name_bl" => "রাঙ্গামাটি সদর", "name_en" => " Rangamati Sadar"],
    ["district_id" => 53, "name_bl" => "নানিয়াচর", "name_en" => " Naniyachar"],
    ["district_id" => 53, "name_bl" => "লংগদু", "name_en" => " Longodhu"],
    ["district_id" => 53, "name_bl" => "বাঘাইছড়ি", "name_en" => " Baghaichori"],
    ["district_id" => 53, "name_bl" => "বড়কাল", "name_en" => " Borokal"],
    ["district_id" => 53, "name_bl" => "জুরাছড়ি", "name_en" => " Jurchari"],
    ["district_id" => 53, "name_bl" => "বিলাইছড়ি", "name_en" => " Bilaichori"],
    ["district_id" => 53, "name_bl" => "রাজসথলি", "name_en" => " Rajostholi"],
    ["district_id" => 54, "name_bl" => "রাজবাড়ী সদর", "name_en" => " Rajbari Sadar"],
    ["district_id" => 54, "name_bl" => "গোয়ালন্দ", "name_en" => " Goalanda"],
    ["district_id" => 54, "name_bl" => "পানগাছা", "name_en" => " pangsha"],
    ["district_id" => 54, "name_bl" => "বালিয়াকান্দি", "name_en" => " Baliakandi"],
    ["district_id" => 54, "name_bl" => "কালুখালি", "name_en" => " Kalukhali"],
    ["district_id" => 55, "name_bl" => "পবা", "name_en" => " Paba"],
    ["district_id" => 55, "name_bl" => "মহনপুর", "name_en" => " Mohonpur"],
    ["district_id" => 55, "name_bl" => "চারঘাট", "name_en" => " Charghat"],
    ["district_id" => 55, "name_bl" => "পুঠিয়া ", "name_en" => " Putia"],
    ["district_id" => 55, "name_bl" => "বাঘা", "name_en" => " Bagha"],
    ["district_id" => 55, "name_bl" => "গোদাগাড়ী ", "name_en" => " Godagari"],
    ["district_id" => 55, "name_bl" => "তানড়", "name_en" => " Tanor"],
    ["district_id" => 55, "name_bl" => "বাগমারা", "name_en" => " Bagmara"],
    ["district_id" => 56, "name_bl" => "লাকসামপুর সদর", "name_en" => " Lakshmipur Sadar"],
    ["district_id" => 56, "name_bl" => "কলম নগর", "name_en" => " Kamol Nagar"],
    ["district_id" => 56, "name_bl" => "রায়পুুর", "name_en" => " Raipur"],
    ["district_id" => 56, "name_bl" => "রামগাতি", "name_en" => " Ramgati"],
    ["district_id" => 56, "name_bl" => "রামগঞ্জ", "name_en" => " Ramganj"],
    ["district_id" => 57, "name_bl" => "লালমনিরহাট সদর", "name_en" => " Lalmonirhat Sadar"],
    ["district_id" => 57, "name_bl" => "অদিতমারি", "name_en" => " Aditmari"],
    ["district_id" => 57, "name_bl" => "হাতিবান্দা", "name_en" => " Hatibanda"],
    ["district_id" => 57, "name_bl" => "পাটগ্রাম", "name_en" => " Patgram"],
    ["district_id" => 58, "name_bl" => "শরিয়তপুর সদর", "name_en" => " Shariatpur Sadar"],
    ["district_id" => 58, "name_bl" => "জাজিরা", "name_en" => " Jajira"],
    ["district_id" => 58, "name_bl" => "নারিয়া", "name_en" => " Naria"],
    ["district_id" => 58, "name_bl" => "ভেদরগঞ্জ", "name_en" => " Vedorganj"],
    ["district_id" => 58, "name_bl" => "ডামুড্যা", "name_en" => " Damudya"],
    ["district_id" => 58, "name_bl" => "গোঁসাইরহাট", "name_en" => " Gosairhat"],
    ["district_id" => 59, "name_bl" => "শেরপুর সদর", "name_en" => " Sherpur Sadar"],
    ["district_id" => 59, "name_bl" => "নলিতাবাড়ি", "name_en" => " Nalitabari"],
    ["district_id" => 59, "name_bl" => "শ্রীবরদী", "name_en" => " Sreebordi"],
    ["district_id" => 59, "name_bl" => "নকলা", "name_en" => " Nokla"],
    ["district_id" => 59, "name_bl" => "ঝিনাইগাতী", "name_en" => " Jhinaigati"],
    ["district_id" => 60, "name_bl" => "সতক্ষিরা সদর", "name_en" => " Satkhira Sadar"],
    ["district_id" => 60, "name_bl" => "কলারোয়া", "name_en" => " Kolaroa"],
    ["district_id" => 60, "name_bl" => "আসাশুনি", "name_en" => " Ashasuni"],
    ["district_id" => 60, "name_bl" => "শ্যামনগর", "name_en" => " Shamnagar"],
    ["district_id" => 60, "name_bl" => "দেবনাথ", "name_en" => " Debhata"],
    ["district_id" => 61, "name_bl" => "সিরাজগঞ্জ সদর", "name_en" => " Sirajganj Sadar"],
    ["district_id" => 61, "name_bl" => "কাজীপুর", "name_en" => " Kajipur"],
    ["district_id" => 61, "name_bl" => "রায়গঞ্জ", "name_en" => " Raiganj"],
    ["district_id" => 61, "name_bl" => "বেলকুচি", "name_en" => " Belkuchi"],
    ["district_id" => 61, "name_bl" => "তারাশ", "name_en" => " Tarash"],
    ["district_id" => 61, "name_bl" => "শাহজাদপুর", "name_en" => " Shahjadpur"],
    ["district_id" => 61, "name_bl" => "উল্লাপাড়া", "name_en" => " Ullapara"],
    ["district_id" => 61, "name_bl" => "কামারখন্দ", "name_en" => " kamarkhanda"],
    ["district_id" => 34, "name_bl" => "কাউখালী", "name_en" => " Chauhali"],
    ["district_id" => 62, "name_bl" => "সিলেট", "name_en" => " Sylhet Sadar"],
    ["district_id" => 62, "name_bl" => "জয়ন্তপুর", "name_en" => " Joyontopur"],
    ["district_id" => 62, "name_bl" => "দক্ষিন সুরমা", "name_en" => " Dokkhin Surma"],
    ["district_id" => 62, "name_bl" => "গোলাপগঞ্জ", "name_en" => " Gopalgonj"],
    ["district_id" => 62, "name_bl" => "বিশ্বনাথ", "name_en" => " Bisshonath"],
    ["district_id" => 30, "name_bl" => "কোম্পানিগঞ্জ", "name_en" => " Companigonj"],
    ["district_id" => 62, "name_bl" => "গোয়াইনঘাট", "name_en" => " GoainGhat"],
    ["district_id" => 62, "name_bl" => "ফেঞ্চুগঞ্জ", "name_en" => " Fenchugonj"],
    ["district_id" => 62, "name_bl" => "বিয়ানীবাজার", "name_en" => " Bianibazar"],
    ["district_id" => 62, "name_bl" => "ওসমানিনগর", "name_en" => " OsmaniNagar"],
    ["district_id" => 62, "name_bl" => "জকিগঞ্জ", "name_en" => " Jokiganj"],
    ["district_id" => 62, "name_bl" => "বালাগঞ্জ", "name_en" => " Balaganj"],
    ["district_id" => 62, "name_bl" => "কানাইঘাট", "name_en" => " Kanaighat"],
    ["district_id" => 63, "name_bl" => "সুনামগঞ্জ সদর", "name_en" => " Sunamganj Sadar"],
    ["district_id" => 63, "name_bl" => "দক্ষিন সুুনামগঞ্জ", "name_en" => " Dokkhin Sunamganj"],
    ["district_id" => 63, "name_bl" => "বিশ্বম্ভরপুর", "name_en" => " Bisshomvorpur"],
    ["district_id" => 63, "name_bl" => "ছাতক", "name_en" => " Chatok"],
    ["district_id" => 63, "name_bl" => "জগন্নতাথপুর", "name_en" => " Jagannathpur"],
    ["district_id" => 63, "name_bl" => "তাহিরপুর", "name_en" => " Tahirpur"],
    ["district_id" => 63, "name_bl" => "ধার্মপাশা", "name_en" => " Dharmapasha"],
    ["district_id" => 63, "name_bl" => "জামালগঞ্জ", "name_en" => " Jamalganj"],
    ["district_id" => 63, "name_bl" => "শাল্লা ", "name_en" => " Shalla"],
    ["district_id" => 63, "name_bl" => "দিরাই", "name_en" => " Derai"],
    ["district_id" => 63, "name_bl" => "দোয়ারাবাজার ", "name_en" => " Doarabazar"],
    ["district_id" => 64, "name_bl" => "হবিগঞ্জ সদর", "name_en" => " Hobiganj Sadar"],
    ["district_id" => 64, "name_bl" => "লাখাই", "name_en" => " Lakhai"],
    ["district_id" => 64, "name_bl" => "নবীগঞ্জ", "name_en" => " Nobiganj"],
    ["district_id" => 64, "name_bl" => "আজমিরীগঞ্জ", "name_en" => " Ajmiriganj"],
    ["district_id" => 64, "name_bl" => "বানিয়াচং", "name_en" => " Baniachang"],
    ["district_id" => 64, "name_bl" => "মাধবপুর", "name_en" => " Madhobpur"],
    ["district_id" => 64, "name_bl" => "বাহুবল", "name_en" => " Bahubal"],
    ["district_id" => 64, "name_bl" => "চুনারুঘাট", "name_en" => " Chunarughat"],
];
